import brasaoPCCE from '../assets/brasao-pcce.png';


export const PCCE_LOGO_URL = brasaoPCCE;

function addNucleoOperacionalOption(mapaDepartamentos) {
    Object.entries(mapaDepartamentos).forEach(([sigla, unidades]) => {
        const possuiNucleoOperacional = unidades.some((unidade) =>
            /N\.?\s*O\b|NUCLEO OPERACIONAL|NÚCLEO OPERACIONAL/i.test(unidade)
        );

        if (!possuiNucleoOperacional) {
            unidades.unshift(`NÚCLEO OPERACIONAL - ${sigla}`);
        }
    });
}

// Organograma completo da PCCE
export const ORGANOGRAMA = {
    "DTO": ["SUPERVISÃO", "APOIO"],
    "DEPATRI": [
        "DEPATRI",
        "NÚCLEO OPERACIONAL DO DEPATRI - DEPATRI",
        "NÚCLEO OPERACIONAL DEPATRI - DEPATRI",
        "NÚCLEO MEU CELULAR - DEPATRI",
        "Delegacia de Polícia Civil Antissequestro",
        "Delegacia de Polícia Civil de Defraudações e Falsificações",
        "Delegacia de Polícia Civil de Roubos e Furtos",
        "Delegacia de Polícia Civil de Roubos e Furtos de Veículos"
    ],
    "DHPP": [
        "1ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "2ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "3ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "4ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "5ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "6ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "7ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "8ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "9ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "10ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "Delegacia de Polícia Civil de Homicídios Contra Agentes de Segurança Pública",
        "Delegacia de Polícia Civil de Pessoas Desaparecidas",
        "DHPP Caucaia",
        "DHPP Maracanaú",
        "DHPP Maranguape"
    ],
    "DPC": [
        "1ª Delegacia de Polícia Civil da Capital",
        "2ª Delegacia de Polícia Civil da Capital",
        "3ª Delegacia de Polícia Civil da Capital",
        "4ª Delegacia de Polícia Civil da Capital",
        "5ª Delegacia de Polícia Civil da Capital",
        "6ª Delegacia de Polícia Civil da Capital",
        "7ª Delegacia de Polícia Civil da Capital",
        "8ª Delegacia de Polícia Civil da Capital",
        "9ª Delegacia de Polícia Civil da Capital",
        "10ª Delegacia de Polícia Civil da Capital",
        "11ª Delegacia de Polícia Civil da Capital",
        "12ª Delegacia de Polícia Civil da Capital",
        "13ª Delegacia de Polícia Civil da Capital",
        "14ª Delegacia de Polícia Civil da Capital",
        "15ª Delegacia de Polícia Civil da Capital",
        "16ª Delegacia de Polícia Civil da Capital",
        "17ª Delegacia de Polícia Civil da Capital",
        "18ª Delegacia de Polícia Civil da Capital",
        "19ª Delegacia de Polícia Civil da Capital",
        "20ª Delegacia de Polícia Civil da Capital",
        "21ª Delegacia de Polícia Civil da Capital",
        "22ª Delegacia de Polícia Civil da Capital",
        "23ª Delegacia de Polícia Civil da Capital",
        "24ª Delegacia de Polícia Civil da Capital",
        "25ª Delegacia de Polícia Civil da Capital",
        "1ª Seccional da Capital",
        "2ª Seccional da Capital",
        "3ª Seccional da Capital",
        "4ª Seccional da Capital",
        "5ª Seccional da Capital"
    ],
    "DPM": [
        "1ª Delegacia de Polícia Civil de Caucaia",
        "2ª Delegacia de Polícia Civil de Caucaia",
        "3ª Delegacia de Polícia Civil de Caucaia",
        "4ª Delegacia de Polícia Civil de Caucaia",
        "5ª Delegacia de Polícia Civil de Caucaia",
        "1ª Delegacia de Polícia Civil de Maracanaú",
        "2ª Delegacia de Polícia Civil de Maracanaú",
        "3ª Delegacia de Polícia Civil de Maracanaú",
        "4ª Delegacia de Polícia Civil de Maracanaú",
        "5ª Delegacia de Polícia Civil de Maracanaú",
        "6ª Delegacia de Polícia Civil de Maracanaú",
        "1ª Delegacia de Polícia Civil de Pacatuba",
        "2ª Delegacia de Polícia Civil de Pacatuba",
        "Delegacia de Polícia Civil de Aquiraz",
        "Delegacia de Polícia Civil de Cascavel",
        "Delegacia de Polícia Civil de Chorozinho",
        "Delegacia de Polícia Civil de Eusébio",
        "Delegacia de Polícia Civil de Guaiúba",
        "Delegacia de Polícia Civil de Horizonte",
        "Delegacia de Polícia Civil de Itaitinga",
        "Delegacia de Polícia Civil de Maranguape",
        "Delegacia de Polícia Civil de Pacajus",
        "Delegacia de Polícia Civil de Paracuru",
        "Delegacia de Polícia Civil de Paraipaba",
        "Delegacia de Polícia Civil de Pindoretama",
        "Delegacia de Polícia Civil de São Gonçalo do Amarante",
        "Delegacia de Polícia Civil de Trairí",
        "1ª Seccional da Região Metropolitana",
        "2ª Seccional da Região Metropolitana",
        "3ª Seccional da Região Metropolitana",
        "4ª Seccional da Região Metropolitana",
        "5ª Seccional da Região Metropolitana",
        "6ª Seccional da Região Metropolitana"
    ],
    "DPI NORTE": [
        "1ª Delegacia de Polícia Civil de Sobral",
        "2ª Delegacia de Polícia Civil de Sobral",
        "Delegacia de Civil Polícia de Independência",
        "Delegacia de Polícia Civil de Acaraú",
        "Delegacia de Polícia Civil de Amontada",
        "Delegacia de Polícia Civil de Aracoiaba",
        "Delegacia de Polícia Civil de Barreira",
        "Delegacia de Polícia Civil de Baturité",
        "Delegacia de Polícia Civil de Bela Cruz",
        "Delegacia de Polícia Civil de Boa Viagem",
        "Delegacia de Polícia Civil de Camocim",
        "Delegacia de Polícia Civil de Canindé",
        "Delegacia de Polícia Civil de Chaval",
        "Delegacia de Polícia Civil de Coreaú",
        "Delegacia de Polícia Civil de Crateús",
        "Delegacia de Polícia Civil de Cruz",
        "Delegacia de Polícia Civil de Forquilha",
        "Delegacia de Polícia Civil de Granja",
        "Delegacia de Polícia Civil de Guaraciaba do Norte",
        "Delegacia de Polícia Civil de Guaramiranga",
        "Delegacia de Polícia Civil de Ipu",
        "Delegacia de Polícia Civil de Ipueiras",
        "Delegacia de Polícia Civil de Itapajé",
        "Delegacia de Polícia Civil de Itapipoca",
        "Delegacia de Polícia Civil de Itarema",
        "Delegacia de Polícia Civil de Jijoca de Jericoacoara",
        "Delegacia de Polícia Civil de Marco",
        "Delegacia de Polícia Civil de Massapê",
        "Delegacia de Polícia Civil de Monsenhor Tabosa",
        "Delegacia de Polícia Civil de Nova Russas",
        "Delegacia de Polícia Civil de Novo Oriente",
        "Delegacia de Polícia Civil de Ocara",
        "Delegacia de Polícia Civil de Pacujá",
        "Delegacia de Polícia Civil de Pentecoste",
        "Delegacia de Polícia Civil de Redenção",
        "Delegacia de Polícia Civil de Santa Quitéria",
        "Delegacia de Polícia Civil de Santana do Acaraú",
        "Delegacia de Polícia Civil de São Benedito",
        "Delegacia de Polícia Civil de Tamboril",
        "Delegacia de Polícia Civil de Tianguá",
        "Delegacia de Polícia Civil de Ubajara",
        "Delegacia de Polícia Civil de Uruburetama",
        "Delegacia de Polícia Civil de Uruoca",
        "Delegacia de Polícia Civil de Varjota",
        "Delegacia de Polícia Civil de Viçosa do Ceará",
        "1ª Seccional do Interior Norte",
        "2ª Seccional do Interior Norte",
        "3ª Seccional do Interior Norte",
        "4ª Seccional do Interior Norte"
    ],
    "DPI SUL": [
        "1ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "2ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Acopiara",
        "Delegacia de Polícia Civil de Alto Santo",
        "Delegacia de Polícia Civil de Aracati",
        "Delegacia de Polícia Civil de Araripe",
        "Delegacia de Polícia Civil de Assaré",
        "Delegacia de Polícia Civil de Aurora",
        "Delegacia de Polícia Civil de Banabuiú",
        "Delegacia de Polícia Civil de Barbalha",
        "Delegacia de Polícia Civil de Barro",
        "Delegacia de Polícia Civil de Beberibe",
        "Delegacia de Polícia Civil de Brejo Santo",
        "Delegacia de Polícia Civil de Campos Sales",
        "Delegacia de Polícia Civil de Caririaçu",
        "Delegacia de Polícia Civil de Cedro",
        "Delegacia de Polícia Civil de Crato",
        "Delegacia de Polícia Civil de Farias Brito",
        "Delegacia de Polícia Civil de Icapuí",
        "Delegacia de Polícia Civil de Icó",
        "Delegacia de Polícia Civil de Iguatu",
        "Delegacia de Polícia Civil de Ipaumirim",
        "Delegacia de Polícia Civil de Iracema",
        "Delegacia de Polícia Civil de Jaguaretama",
        "Delegacia de Polícia Civil de Jaguaribe",
        "Delegacia de Polícia Civil de Jaguaruana",
        "Delegacia de Polícia Civil de Jardim",
        "Delegacia de Polícia Civil de Jucás",
        "Delegacia de Polícia Civil de Lavras da Mangabeira",
        "Delegacia de Polícia Civil de Limoeiro do Norte",
        "Delegacia de Polícia Civil de Mauriti",
        "Delegacia de Polícia Civil de Milagres",
        "Delegacia de Polícia Civil de Missão Velha",
        "Delegacia de Polícia Civil de Mombaça",
        "Delegacia de Polícia Civil de Morada Nova",
        "Delegacia de Polícia Civil de Nova Olinda",
        "Delegacia de Polícia Civil de Orós",
        "Delegacia de Polícia Civil de Parambu",
        "Delegacia de Polícia Civil de Pedra Branca",
        "Delegacia de Polícia Civil de Penaforte",
        "Delegacia de Polícia Civil de Quiterianópolis",
        "Delegacia de Polícia Civil de Quixadá",
        "Delegacia de Polícia Civil de Quixeramobim",
        "Delegacia de Polícia Civil de Russas",
        "Delegacia de Polícia Civil de Saboeiro",
        "Delegacia de Polícia Civil de São João do Jaguaribe",
        "Delegacia de Polícia Civil de Senador Pompeu",
        "Delegacia de Polícia Civil de Solonópole",
        "Delegacia de Polícia Civil de Tabuleiro do Norte",
        "Delegacia de Polícia Civil de Tauá",
        "Delegacia de Polícia Civil de Várzea Alegre",
        "1ª Seccional do Interior Sul",
        "2ª Seccional do Interior Sul",
        "3ª Seccional do Interior Sul",
        "4ª Seccional do Interior Sul",
        "5ª Seccional do Interior Sul"
    ],
    "DPE": [
        "Delegacia de Polícia Civil de Assuntos Internos",
        "Delegacia de Polícia Civil de Capturas e Polinter",
        "Delegacia de Polícia Civil de Proteção ao Consumidor",
        "Delegacia de Polícia Civil de Proteção ao Meio Ambiente",
        "Delegacia de Polícia Civil de Proteção ao Turista",
        "Delegacia de Polícia Civil de Repressão aos Crimes Cibernéticos",
        "Delegacia de Polícia Civil do Aeroporto Pinto Martins",
        "Delegacia do Torcedor e dos Grandes Eventos"
    ],
    "DPGV": [
        "1ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "2ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "Delegacia de Polícia Civil da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Combate à Exploração da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Defesa da Mulher de Caucaia",
        "Delegacia de Polícia Civil de Defesa da Mulher de Crato",
        "Delegacia de Polícia Civil de Defesa da Mulher de Icó",
        "Delegacia de Polícia Civil de Defesa da Mulher de Iguatu",
        "Delegacia de Polícia Civil de Defesa da Mulher de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Defesa da Mulher de Maracanaú",
        "Delegacia de Polícia Civil de Defesa da Mulher de Pacatuba",
        "Delegacia de Polícia Civil de Defesa da Mulher de Quixadá",
        "Delegacia de Polícia Civil de Defesa da Mulher de Sobral",
        "Delegacia de Polícia Civil de Proteção ao Idoso e Pessoa com Deficiência",
        "Delegacia de Polícia Civil de Repressão aos Crimes de Intolerância Racial, Religiosa, por Identidade de Gênero ou Orientação Sexual"
    ],
    "DRA": [
        "Delegacia de Polícia Civil de Combate à Corrupção",
        "Delegacia de Polícia Civil de Combate aos Crimes Contra a Ordem Tributária",
        "Delegacia de Polícia Civil de Combate aos Crimes de Lavagem de Dinheiro"
    ],
    "DRCO": [
        "Delegacia de Combate ao Tráfico de Armas, Munições e Explosivos",
        "Delegacia de Polícia Civil de Narcóticos",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Norte",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Sul"
    ],
    "ASJ": ["Assessoria Jurídica"],
    "COGEP": [], 
    "COTIC": [], 
    "COLOG": ["COLOG"], 
    "CODIP": [], 
    "GAB": [], 
    "CORE": ["Coordenadoria de Operações e Recursos Especiais"]
};

addNucleoOperacionalOption(ORGANOGRAMA);

// Mapeamento completo de Delegacias por Departamento (oficial PCCE)
export const DEPARTMENTS = {
    "DEPATRI": [
        "DEPATRI",
        "NÚCLEO OPERACIONAL DO DEPATRI - DEPATRI",
        "NÚCLEO OPERACIONAL DEPATRI - DEPATRI",
        "NÚCLEO MEU CELULAR - DEPATRI",
        "Delegacia de Polícia Civil Antissequestro",
        "Delegacia de Polícia Civil de Defraudações e Falsificações",
        "Delegacia de Polícia Civil de Roubos e Furtos",
        "Delegacia de Polícia Civil de Roubos e Furtos de Veículos"
    ],
    "DHPP": [
        "1ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "2ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "3ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "4ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "5ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "6ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "7ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "8ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "9ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "10ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "Delegacia de Polícia Civil de Homicídios Contra Agentes de Segurança Pública",
        "Delegacia de Polícia Civil de Pessoas Desaparecidas",
        "DHPP Caucaia",
        "DHPP Maracanaú",
        "DHPP Maranguape"
    ],
    "DPC": [
        "1ª Delegacia de Polícia Civil da Capital",
        "2ª Delegacia de Polícia Civil da Capital",
        "3ª Delegacia de Polícia Civil da Capital",
        "4ª Delegacia de Polícia Civil da Capital",
        "5ª Delegacia de Polícia Civil da Capital",
        "6ª Delegacia de Polícia Civil da Capital",
        "7ª Delegacia de Polícia Civil da Capital",
        "8ª Delegacia de Polícia Civil da Capital",
        "9ª Delegacia de Polícia Civil da Capital",
        "10ª Delegacia de Polícia Civil da Capital",
        "11ª Delegacia de Polícia Civil da Capital",
        "12ª Delegacia de Polícia Civil da Capital",
        "13ª Delegacia de Polícia Civil da Capital",
        "14ª Delegacia de Polícia Civil da Capital",
        "15ª Delegacia de Polícia Civil da Capital",
        "16ª Delegacia de Polícia Civil da Capital",
        "17ª Delegacia de Polícia Civil da Capital",
        "18ª Delegacia de Polícia Civil da Capital",
        "19ª Delegacia de Polícia Civil da Capital",
        "20ª Delegacia de Polícia Civil da Capital",
        "21ª Delegacia de Polícia Civil da Capital",
        "22ª Delegacia de Polícia Civil da Capital",
        "23ª Delegacia de Polícia Civil da Capital",
        "24ª Delegacia de Polícia Civil da Capital",
        "25ª Delegacia de Polícia Civil da Capital",
        "1ª Seccional da Capital",
        "2ª Seccional da Capital",
        "3ª Seccional da Capital",
        "4ª Seccional da Capital",
        "5ª Seccional da Capital"
    ],
    "DPM": [
        "1ª Delegacia de Polícia Civil de Caucaia",
        "2ª Delegacia de Polícia Civil de Caucaia",
        "3ª Delegacia de Polícia Civil de Caucaia",
        "4ª Delegacia de Polícia Civil de Caucaia",
        "5ª Delegacia de Polícia Civil de Caucaia",
        "1ª Delegacia de Polícia Civil de Maracanaú",
        "2ª Delegacia de Polícia Civil de Maracanaú",
        "3ª Delegacia de Polícia Civil de Maracanaú",
        "4ª Delegacia de Polícia Civil de Maracanaú",
        "5ª Delegacia de Polícia Civil de Maracanaú",
        "6ª Delegacia de Polícia Civil de Maracanaú",
        "1ª Delegacia de Polícia Civil de Pacatuba",
        "2ª Delegacia de Polícia Civil de Pacatuba",
        "Delegacia de Polícia Civil de Aquiraz",
        "Delegacia de Polícia Civil de Cascavel",
        "Delegacia de Polícia Civil de Chorozinho",
        "Delegacia de Polícia Civil de Eusébio",
        "Delegacia de Polícia Civil de Guaiúba",
        "Delegacia de Polícia Civil de Horizonte",
        "Delegacia de Polícia Civil de Itaitinga",
        "Delegacia de Polícia Civil de Maranguape",
        "Delegacia de Polícia Civil de Pacajus",
        "Delegacia de Polícia Civil de Paracuru",
        "Delegacia de Polícia Civil de Paraipaba",
        "Delegacia de Polícia Civil de Pindoretama",
        "Delegacia de Polícia Civil de São Gonçalo do Amarante",
        "Delegacia de Polícia Civil de Trairí",
        "1ª Seccional da Região Metropolitana",
        "2ª Seccional da Região Metropolitana",
        "3ª Seccional da Região Metropolitana",
        "4ª Seccional da Região Metropolitana",
        "5ª Seccional da Região Metropolitana",
        "6ª Seccional da Região Metropolitana"
    ],
    "DPI NORTE": [
        "1ª Delegacia de Polícia Civil de Sobral",
        "2ª Delegacia de Polícia Civil de Sobral",
        "Delegacia de Civil Polícia de Independência",
        "Delegacia de Polícia Civil de Acaraú",
        "Delegacia de Polícia Civil de Amontada",
        "Delegacia de Polícia Civil de Aracoiaba",
        "Delegacia de Polícia Civil de Barreira",
        "Delegacia de Polícia Civil de Baturité",
        "Delegacia de Polícia Civil de Bela Cruz",
        "Delegacia de Polícia Civil de Boa Viagem",
        "Delegacia de Polícia Civil de Camocim",
        "Delegacia de Polícia Civil de Canindé",
        "Delegacia de Polícia Civil de Chaval",
        "Delegacia de Polícia Civil de Coreaú",
        "Delegacia de Polícia Civil de Crateús",
        "Delegacia de Polícia Civil de Cruz",
        "Delegacia de Polícia Civil de Forquilha",
        "Delegacia de Polícia Civil de Granja",
        "Delegacia de Polícia Civil de Guaraciaba do Norte",
        "Delegacia de Polícia Civil de Guaramiranga",
        "Delegacia de Polícia Civil de Ipu",
        "Delegacia de Polícia Civil de Ipueiras",
        "Delegacia de Polícia Civil de Itapajé",
        "Delegacia de Polícia Civil de Itapipoca",
        "Delegacia de Polícia Civil de Itarema",
        "Delegacia de Polícia Civil de Jijoca de Jericoacoara",
        "Delegacia de Polícia Civil de Marco",
        "Delegacia de Polícia Civil de Massapê",
        "Delegacia de Polícia Civil de Monsenhor Tabosa",
        "Delegacia de Polícia Civil de Nova Russas",
        "Delegacia de Polícia Civil de Novo Oriente",
        "Delegacia de Polícia Civil de Ocara",
        "Delegacia de Polícia Civil de Pacujá",
        "Delegacia de Polícia Civil de Pentecoste",
        "Delegacia de Polícia Civil de Redenção",
        "Delegacia de Polícia Civil de Santa Quitéria",
        "Delegacia de Polícia Civil de Santana do Acaraú",
        "Delegacia de Polícia Civil de São Benedito",
        "Delegacia de Polícia Civil de Tamboril",
        "Delegacia de Polícia Civil de Tianguá",
        "Delegacia de Polícia Civil de Ubajara",
        "Delegacia de Polícia Civil de Uruburetama",
        "Delegacia de Polícia Civil de Uruoca",
        "Delegacia de Polícia Civil de Varjota",
        "Delegacia de Polícia Civil de Viçosa do Ceará",
        "1ª Seccional do Interior Norte",
        "2ª Seccional do Interior Norte",
        "3ª Seccional do Interior Norte",
        "4ª Seccional do Interior Norte"
    ],
    "DPI SUL": [
        "1ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "2ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Acopiara",
        "Delegacia de Polícia Civil de Alto Santo",
        "Delegacia de Polícia Civil de Aracati",
        "Delegacia de Polícia Civil de Araripe",
        "Delegacia de Polícia Civil de Assaré",
        "Delegacia de Polícia Civil de Aurora",
        "Delegacia de Polícia Civil de Banabuiú",
        "Delegacia de Polícia Civil de Barbalha",
        "Delegacia de Polícia Civil de Barro",
        "Delegacia de Polícia Civil de Beberibe",
        "Delegacia de Polícia Civil de Brejo Santo",
        "Delegacia de Polícia Civil de Campos Sales",
        "Delegacia de Polícia Civil de Caririaçu",
        "Delegacia de Polícia Civil de Cedro",
        "Delegacia de Polícia Civil de Crato",
        "Delegacia de Polícia Civil de Farias Brito",
        "Delegacia de Polícia Civil de Icapuí",
        "Delegacia de Polícia Civil de Icó",
        "Delegacia de Polícia Civil de Iguatu",
        "Delegacia de Polícia Civil de Ipaumirim",
        "Delegacia de Polícia Civil de Iracema",
        "Delegacia de Polícia Civil de Jaguaretama",
        "Delegacia de Polícia Civil de Jaguaribe",
        "Delegacia de Polícia Civil de Jaguaruana",
        "Delegacia de Polícia Civil de Jardim",
        "Delegacia de Polícia Civil de Jucás",
        "Delegacia de Polícia Civil de Lavras da Mangabeira",
        "Delegacia de Polícia Civil de Limoeiro do Norte",
        "Delegacia de Polícia Civil de Mauriti",
        "Delegacia de Polícia Civil de Milagres",
        "Delegacia de Polícia Civil de Missão Velha",
        "Delegacia de Polícia Civil de Mombaça",
        "Delegacia de Polícia Civil de Morada Nova",
        "Delegacia de Polícia Civil de Nova Olinda",
        "Delegacia de Polícia Civil de Orós",
        "Delegacia de Polícia Civil de Parambu",
        "Delegacia de Polícia Civil de Pedra Branca",
        "Delegacia de Polícia Civil de Penaforte",
        "Delegacia de Polícia Civil de Quiterianópolis",
        "Delegacia de Polícia Civil de Quixadá",
        "Delegacia de Polícia Civil de Quixeramobim",
        "Delegacia de Polícia Civil de Russas",
        "Delegacia de Polícia Civil de Saboeiro",
        "Delegacia de Polícia Civil de São João do Jaguaribe",
        "Delegacia de Polícia Civil de Senador Pompeu",
        "Delegacia de Polícia Civil de Solonópole",
        "Delegacia de Polícia Civil de Tabuleiro do Norte",
        "Delegacia de Polícia Civil de Tauá",
        "Delegacia de Polícia Civil de Várzea Alegre",
        "1ª Seccional do Interior Sul",
        "2ª Seccional do Interior Sul",
        "3ª Seccional do Interior Sul",
        "4ª Seccional do Interior Sul",
        "5ª Seccional do Interior Sul"
    ],
    "DPE": [
        "Delegacia de Polícia Civil de Assuntos Internos",
        "Delegacia de Polícia Civil de Capturas e Polinter",
        "Delegacia de Polícia Civil de Proteção ao Consumidor",
        "Delegacia de Polícia Civil de Proteção ao Meio Ambiente",
        "Delegacia de Polícia Civil de Proteção ao Turista",
        "Delegacia de Polícia Civil de Repressão aos Crimes Cibernéticos",
        "Delegacia de Polícia Civil do Aeroporto Pinto Martins",
        "Delegacia do Torcedor e dos Grandes Eventos"
    ],
    "DPGV": [
        "1ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "2ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "Delegacia de Polícia Civil da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Combate à Exploração da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Defesa da Mulher de Caucaia",
        "Delegacia de Polícia Civil de Defesa da Mulher de Crato",
        "Delegacia de Polícia Civil de Defesa da Mulher de Icó",
        "Delegacia de Polícia Civil de Defesa da Mulher de Iguatu",
        "Delegacia de Polícia Civil de Defesa da Mulher de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Defesa da Mulher de Maracanaú",
        "Delegacia de Polícia Civil de Defesa da Mulher de Pacatuba",
        "Delegacia de Polícia Civil de Defesa da Mulher de Quixadá",
        "Delegacia de Polícia Civil de Defesa da Mulher de Sobral",
        "Delegacia de Polícia Civil de Proteção ao Idoso e Pessoa com Deficiência",
        "Delegacia de Polícia Civil de Repressão aos Crimes de Intolerância Racial, Religiosa, por Identidade de Gênero ou Orientação Sexual"
    ],
    "DRA": [
        "Delegacia de Polícia Civil de Combate à Corrupção",
        "Delegacia de Polícia Civil de Combate aos Crimes Contra a Ordem Tributária",
        "Delegacia de Polícia Civil de Combate aos Crimes de Lavagem de Dinheiro"
    ],
    "DRCO": [
        "Delegacia de Combate ao Tráfico de Armas, Munições e Explosivos",
        "Delegacia de Polícia Civil de Narcóticos",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Norte",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Sul"
    ],
    "ASJ": ["Assessoria Jurídica"],
    "CORE": ["Coordenadoria de Operações e Recursos Especiais"],
    "DTO": ["DTO"],
    "CODIP": ["CODIP"],
    "COTIC": ["COTIC"],
    "COGEP": ["COGEP"],
    "COLOG": ["COLOG"],
    "GDGPC": ["GDGPC"],
    "AESP": ["AESP"],
    "COAFI": ["COAFI"],
    "CIOPAER": ["CIOPAER"],
    "ASCON": ["ASCON"],
    "COREG": ["COREG"]
};

addNucleoOperacionalOption(DEPARTMENTS);

export const PAY_RATES = {
    "OIP": {
        "A": { dia: 34.42, noite: 44.75 },
        "B": { dia: 34.42, noite: 44.75 },
        "C": { dia: 34.42, noite: 44.75 },
        "D": { dia: 34.42, noite: 44.75 }
    },
    "DPC": {
        "Especial": { dia: 48.18, noite: 62.63 }
    }
};


export const AIS_OPTIONS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34];
export const DPC_LIST = ["KLEVER FARIAS", "ALCEU VIANA", "HUGGO LEONARDO", "LUIS JUNIOR", "EVNA AMERICA", "ROBERTA FROTA", "JOÃO GABRIEL", "KEYLA LACERDA", "WILSON CAMELO", "JULIUS BERNARDO"];
export const OIP_LIST = ["JARBAS", "LUCAS", "PAULO JUNIOR", "ALEX", "ROGERIO", "JOÃO PAULO CAVALCANTE TEIXEIRA"];
export const BRIEFING_LOCATIONS = ["Polícia Civil - CISP", ...DEPARTMENTS.DPC];
export const WEAPON_TYPES = ["PISTOLA", "REVÓLVER", "CARABINA", "METRALHADORA", "FUZIL", "ESCOPETA"];
export const AMMO_TYPES = ["9mm", ".40", ".380", ".38", ".32", ".22", "12", "5.56", "7.62", ".50", ".30"];
export const DRUG_TYPES = ["MACONHA", "HAXIXE", "COCAÍNA", "HEROÍNA", "CRACK", "SKANK", "LSD", "ECSTASY", "ANFETAMINAS", "ANABOLIZANTES"];
export const PRISON_TYPES = { 'preventiva': 'Preventiva', 'temporaria': 'Temporária', 'definitiva': 'Definitiva', 'civil': 'Civil', 'flagrante': 'Flagrante' };
export const DEFAULT_VAGAS_RULES = { night_weekday: 8, night_weekend_holiday: 10, day_weekend_holiday: 2 };

export const AIS_BAIRROS = {
    "1": ["Jaguaruana", "Limoeiro do Norte", "Quixeré", "Russas", "São João do Jaguaribe", "Tabuleiro do Norte"],
    "2": ["Aurora", "Barbalha", "Caririaçu", "Crato", "Farias Brito", "Jardim", "Juazeiro do Norte", "Missão Velha", "Nova Olinda", "Santana do Cariri"],
    "3": ["Alcântaras", "Cariré", "Coreaú", "Forquilha", "Frecheirinha", "Graça", "Groaíras", "Massapê", "Meruoca", "Mucambo", "Pacujá", "Santana do Acaraú", "Senador Sá", "Sobral"],
    "4": ["Boa Viagem", "Canindé", "Caridade", "Itatira", "Madalena", "Paramoti"],
    "5": ["Álvaro Weyne", "Carlito Pamplona", "Centro", "Ellery", "Farias Brito", "Jacarecanga", "Monte Castelo", "Moura Brasil", "São Gerardo"],
    "6": ["Aeroporto", "Benfica", "Bom Futuro", "Couto Fernandes", "Damas", "Demócrito Rocha", "Rachel de Queiroz", "Fátima", "Itaoca", "Itaperi", "Jardim América", "José Bonifácio", "Montese", "Panamericano", "Parangaba", "Parreão", "Serrinha", "Vila Peri", "Vila União"],
    "7": ["Ararendá", "Catunda", "Crateús", "Hidrolândia", "Independência", "Ipaporanga", "Ipu", "Ipueiras", "Monsenhor Tabosa", "Nova Russas", "Novo Oriente", "Pires Ferreira", "Poranga", "Reriutaba", "Santa Quitéria", "Tamboril", "Varjota"],
    "8": ["Aldeota", "Cais do Porto", "Meireles", "Mucuripe", "Varjota", "Vicente Pinzón"],
    "9": ["Banabuiú", "Choró", "Dep. Irapuan Pinheiro", "Ibaretama", "Ibicuitinga", "Jaguaretama", "Milhã", "Morada Nova", "Pedra Branca", "Quixadá", "Quixeramobim", "Senador Pompeu", "Solonópole"],
    "10": ["Acopiara", "Cariús", "Iguatu", "Jucás", "Quixelô", "Saboeiro", "Tarrafas"],
    "11": ["Acaraú", "Amontada", "Apuiarés", "Bela Cruz", "Cruz", "Gen. Sampaio", "Irauçuba", "Itapajé", "Itapipoca", "Itarema", "Jijoca de Jericoacoara", "Marco", "Miraíma", "Morrinhos", "Pentecoste", "Tejuçuoca", "Tururu", "Umirim", "Uruburetama"],
    "12": ["Centro", "Icaraí", "Cumbuco", "Tabuba", "Iparana", "Pacheco", "Jurema", "Parque Soledade", "Nova Cigana", "Araticuba", "Sítios Novos"],
    "13": ["Aiuaba", "Arneiroz", "Catarina", "Mombaça", "Parambu", "Piquet Carneiro", "Quiterianópolis", "Tauá"],
    "14": ["Maracanaú"],
    "15": ["Aquiraz", "Cascavel", "Eusébio", "Pindoretama"],
    "16": ["Ancuri", "Barroso", "Coaçu", "Conj. Palmeiras", "Curió", "Guajeru", "Jangurussu", "Lagoa Redonda", "Messejana", "Pq. Santa Maria", "Paupina", "Pedras", "São Bento"],
    "17": ["Bom Jardim", "Conj. Ceará I", "Conj. Ceará II", "Genibaú", "Granja Lisboa", "Granja Portugal", "Siqueira"],
    "18": ["Amadeu Furtado", "Antônio Bezerra", "Autran Nunes", "Bela Vista", "Bonsucesso", "Dom Lustosa", "Henrique Jorge", "João XXIII", "Jóquei Clube", "Olavo Oliveira", "Padre Andrade", "Parquelândia", "Pici", "Pres. Kennedy", "Quintino Cunha"],
    "19": ["Aerolândia", "Alto da Balança", "Castelão", "Cajazeiras", "Cambeba", "Cid. dos Funcionários", "Dias Macêdo", "Edson Queiroz", "Jd. das Oliveiras", "José de Alencar", "Passaré", "Sabiaguaba", "Sapiranga"],
    "20": ["Barra do Ceará", "Cristo Redentor", "Floresta", "Jardim Guanabara", "Jardim Iracema", "Pirambu", "Vila Velha"],
    "21": ["Aracapé", "Canindezinho", "Conj. Esperança", "Jd. Cearense", "Manoel Sátiro", "Maraponga", "Mondubim", "Pq. Pres. Vargas", "Pq. Santa Rosa", "Planalto Ayrton Senna", "José Walter"],
    "22": ["Cidade 2000", "Cocó", "De Lourdes", "Dionísio Torres", "Eng. Luciano Cavalcante", "Guararapes", "Joaquim Távora", "Papicu", "Praia do Futuro I", "Praia do Futuro II", "Salinas", "Tauape"],
    "23": ["Paracuru", "Paraipaba", "São Luís do Curu", "Trairi", "São Gonçalo do Amarante"],
    "24": ["Guaiúba", "Maranguape", "Pacatuba"],
    "25": ["Chorozinho", "Horizonte", "Itaitinga", "Pacajus"],
    "26": ["Guadalajara", "Potira", "Pq. Albano", "Araturi", "Nova Metrópole", "Arianópoles", "Tabapuá", "Marechal Rondon", "Sede (Rural Leste)", "Mirambé"],
    "27": ["Carnaubal", "Croatá", "Guaraciaba do Norte", "Ibiapina", "São Benedito", "Tianguá", "Ubajara", "Viçosa do Ceará"],
    "28": ["Barroquinha", "Camocim", "Chaval", "Granja", "Martinópole", "Moraújo", "Uruoca"],
    "29": ["Acarape", "Aracoiaba", "Aratuba", "Baturité", "Capistrano", "Guaramiranga", "Itapiúna", "Mulungu", "Ocara", "Pacoti", "Palmácia", "Redenção"],
    "30": ["Aracati", "Beberibe", "Fortim", "Icapuí", "Itaiçaba", "Palhano"],
    "31": ["Alto Santo", "Ereré", "Iracema", "Jaguaribara", "Jaguaribe", "Pereiro", "Potiretama"],
    "32": ["Abaiara", "Barro", "Brejo Santo", "Jati", "Mauriti", "Milagres", "Penaforte", "Porteiras"],
    "33": ["Altaneira", "Antonina do Norte", "Araripe", "Assaré", "Campos Sales", "Potengi", "Salitre"],
    "34": ["Baixio", "Cedro", "Granjeiro", "Icó", "Ipaumirim", "Lavras da Mangabeira", "Orós", "Umari", "Várzea Alegre"]
}

// Outros órgãos e siglas estaduais
export const OUTROS_ORGAOS = ["Ministério Público", "Polícia Civil de Outros Estados"];
export const SIGLAS_ESTADOS = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"];

// Órgãos Externos que podem solicitar operações
export const ORGAOS_EXTERNOS = {
    "MPCE - Ministério Público do Ceará": [],
    "MPPE - Ministério Público de Pernambuco": [],
    "MPBA - Ministério Público da Bahia": [],
    "MPPI - Ministério Público do Piauí": [],
    "PCRN - Polícia Civil do Rio Grande do Norte": [],
    "PCPB - Polícia Civil da Paraíba": [],
    "PCPE - Polícia Civil de Pernambuco": [],
    "PCBA - Polícia Civil da Bahia": [],
    "PCPI - Polícia Civil do Piauí": [],
    "PCMA - Polícia Civil do Maranhão": [],
    "Polícia Federal": [],
    "PRF - Polícia Rodoviária Federal": [],
    "Receita Federal": [],
    "SEFAZ - Secretaria da Fazenda": []
};
export const TIPOS_APOIO = ["Cartório", "Inteligência", "Apoio Logístico"];
export const RESTRICTED_DEPTS = ["COGEP", "COTIC", "COLOG", "CODIP", "GAB", "CORE"];

// Taxas de hora extra
export const HORA_EXTRA_RATES = {
    dpc: { slot1: 47.70, slot2: 62.01 },
    oip: { slot1: 34.08, slot2: 44.30 }
};

// Dados de demandas para operações
export const DEMAND_DATA = {
    tiposPenais: ["Homicídio", "Tráfico de Drogas", "ORCRIM Lavagem de Dinheiro", "Roubo", "Furto", "Outros"],
    modalidades: ["Mandado de Busca e Apreensão Domiciliar", "Mandado de Prisão Preventiva", "Mandado de Prisão Temporária", "Sequestro/Bloqueio de Bens", "Outros"],
    faccoes: ["CV", "GDE", "Neutros", "PCC", "TCP", "Outros"],
    alvosSensiveis: ["Mulher", "Policial", "Político", "Advogado", "Servidor Público", "Outros"],
    apoioOutrosOrgaos: ["MP", "Polícia Militar", "Polícia Federal", "Polícia Rodoviária Federal", "Receita Federal", "SEFAZ", "AMC", "Guarda Municipal"]
};