import brasaoPCCE from '../assets/brasao-pcce.png';


export const PCCE_LOGO_URL = brasaoPCCE;

// Organograma completo da PCCE
export const ORGANOGRAMA = {
    "DTO": ["SUPERVISÃO", "APOIO"],
    "DEPATRI": [
        "Delegacia de Polícia Civil Antissequestro",
        "Delegacia de Polícia Civil de Defraudações e Falsificações",
        "Delegacia de Polícia Civil de Roubos e Furtos",
        "Delegacia de Polícia Civil de Roubos e Furtos de Veículos"
    ],
    "DHPP": [
        "1ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "2ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "3ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "4ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "5ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "6ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "7ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "8ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "9ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "10ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "Delegacia de Polícia Civil de Homicídios Contra Agentes de Segurança Pública",
        "Delegacia de Polícia Civil de Pessoas Desaparecidas"
    ],
    "DPC": [
        "1ª Delegacia de Polícia Civil da Capital",
        "2ª Delegacia de Polícia Civil da Capital",
        "3ª Delegacia de Polícia Civil da Capital",
        "4ª Delegacia de Polícia Civil da Capital",
        "5ª Delegacia de Polícia Civil da Capital",
        "6ª Delegacia de Polícia Civil da Capital",
        "7ª Delegacia de Polícia Civil da Capital",
        "8ª Delegacia de Polícia Civil da Capital",
        "9ª Delegacia de Polícia Civil da Capital",
        "10ª Delegacia de Polícia Civil da Capital",
        "11ª Delegacia de Polícia Civil da Capital",
        "12ª Delegacia de Polícia Civil da Capital",
        "13ª Delegacia de Polícia Civil da Capital",
        "14ª Delegacia de Polícia Civil da Capital",
        "15ª Delegacia de Polícia Civil da Capital",
        "16ª Delegacia de Polícia Civil da Capital",
        "17ª Delegacia de Polícia Civil da Capital",
        "18ª Delegacia de Polícia Civil da Capital",
        "19ª Delegacia de Polícia Civil da Capital",
        "20ª Delegacia de Polícia Civil da Capital",
        "21ª Delegacia de Polícia Civil da Capital",
        "22ª Delegacia de Polícia Civil da Capital",
        "23ª Delegacia de Polícia Civil da Capital",
        "24ª Delegacia de Polícia Civil da Capital",
        "25ª Delegacia de Polícia Civil da Capital",
        "1ª Seccional da Capital",
        "2ª Seccional da Capital",
        "3ª Seccional da Capital",
        "4ª Seccional da Capital",
        "5ª Seccional da Capital"
    ],
    "DPM": [
        "1ª Delegacia de Polícia Civil de Caucaia",
        "2ª Delegacia de Polícia Civil de Caucaia",
        "3ª Delegacia de Polícia Civil de Caucaia",
        "4ª Delegacia de Polícia Civil de Caucaia",
        "5ª Delegacia de Polícia Civil de Caucaia",
        "1ª Delegacia de Polícia Civil de Maracanaú",
        "2ª Delegacia de Polícia Civil de Maracanaú",
        "3ª Delegacia de Polícia Civil de Maracanaú",
        "4ª Delegacia de Polícia Civil de Maracanaú",
        "5ª Delegacia de Polícia Civil de Maracanaú",
        "6ª Delegacia de Polícia Civil de Maracanaú",
        "1ª Delegacia de Polícia Civil de Pacatuba",
        "2ª Delegacia de Polícia Civil de Pacatuba",
        "Delegacia de Polícia Civil de Aquiraz",
        "Delegacia de Polícia Civil de Cascavel",
        "Delegacia de Polícia Civil de Chorozinho",
        "Delegacia de Polícia Civil de Eusébio",
        "Delegacia de Polícia Civil de Guaiúba",
        "Delegacia de Polícia Civil de Horizonte",
        "Delegacia de Polícia Civil de Itaitinga",
        "Delegacia de Polícia Civil de Maranguape",
        "Delegacia de Polícia Civil de Pacajus",
        "Delegacia de Polícia Civil de Paracuru",
        "Delegacia de Polícia Civil de Paraipaba",
        "Delegacia de Polícia Civil de Pindoretama",
        "Delegacia de Polícia Civil de São Gonçalo do Amarante",
        "Delegacia de Polícia Civil de Trairí",
        "1ª Seccional da Região Metropolitana",
        "2ª Seccional da Região Metropolitana",
        "3ª Seccional da Região Metropolitana",
        "4ª Seccional da Região Metropolitana",
        "5ª Seccional da Região Metropolitana",
        "6ª Seccional da Região Metropolitana"
    ],
    "DPI NORTE": [
        "1ª Delegacia de Polícia Civil de Sobral",
        "2ª Delegacia de Polícia Civil de Sobral",
        "Delegacia de Civil Polícia de Independência",
        "Delegacia de Polícia Civil de Acaraú",
        "Delegacia de Polícia Civil de Amontada",
        "Delegacia de Polícia Civil de Aracoiaba",
        "Delegacia de Polícia Civil de Barreira",
        "Delegacia de Polícia Civil de Baturité",
        "Delegacia de Polícia Civil de Bela Cruz",
        "Delegacia de Polícia Civil de Boa Viagem",
        "Delegacia de Polícia Civil de Camocim",
        "Delegacia de Polícia Civil de Canindé",
        "Delegacia de Polícia Civil de Chaval",
        "Delegacia de Polícia Civil de Coreaú",
        "Delegacia de Polícia Civil de Crateús",
        "Delegacia de Polícia Civil de Cruz",
        "Delegacia de Polícia Civil de Forquilha",
        "Delegacia de Polícia Civil de Granja",
        "Delegacia de Polícia Civil de Guaraciaba do Norte",
        "Delegacia de Polícia Civil de Guaramiranga",
        "Delegacia de Polícia Civil de Ipu",
        "Delegacia de Polícia Civil de Ipueiras",
        "Delegacia de Polícia Civil de Itapajé",
        "Delegacia de Polícia Civil de Itapipoca",
        "Delegacia de Polícia Civil de Itarema",
        "Delegacia de Polícia Civil de Jijoca de Jericoacoara",
        "Delegacia de Polícia Civil de Marco",
        "Delegacia de Polícia Civil de Massapê",
        "Delegacia de Polícia Civil de Monsenhor Tabosa",
        "Delegacia de Polícia Civil de Nova Russas",
        "Delegacia de Polícia Civil de Novo Oriente",
        "Delegacia de Polícia Civil de Ocara",
        "Delegacia de Polícia Civil de Pacujá",
        "Delegacia de Polícia Civil de Pentecoste",
        "Delegacia de Polícia Civil de Redenção",
        "Delegacia de Polícia Civil de Santa Quitéria",
        "Delegacia de Polícia Civil de Santana do Acaraú",
        "Delegacia de Polícia Civil de São Benedito",
        "Delegacia de Polícia Civil de Tamboril",
        "Delegacia de Polícia Civil de Tianguá",
        "Delegacia de Polícia Civil de Ubajara",
        "Delegacia de Polícia Civil de Uruburetama",
        "Delegacia de Polícia Civil de Uruoca",
        "Delegacia de Polícia Civil de Varjota",
        "Delegacia de Polícia Civil de Viçosa do Ceará",
        "1ª Seccional do Interior Norte",
        "2ª Seccional do Interior Norte",
        "3ª Seccional do Interior Norte",
        "4ª Seccional do Interior Norte"
    ],
    "DPI SUL": [
        "1ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "2ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Acopiara",
        "Delegacia de Polícia Civil de Alto Santo",
        "Delegacia de Polícia Civil de Aracati",
        "Delegacia de Polícia Civil de Araripe",
        "Delegacia de Polícia Civil de Assaré",
        "Delegacia de Polícia Civil de Aurora",
        "Delegacia de Polícia Civil de Banabuiú",
        "Delegacia de Polícia Civil de Barbalha",
        "Delegacia de Polícia Civil de Barro",
        "Delegacia de Polícia Civil de Beberibe",
        "Delegacia de Polícia Civil de Brejo Santo",
        "Delegacia de Polícia Civil de Campos Sales",
        "Delegacia de Polícia Civil de Caririaçu",
        "Delegacia de Polícia Civil de Cedro",
        "Delegacia de Polícia Civil de Crato",
        "Delegacia de Polícia Civil de Farias Brito",
        "Delegacia de Polícia Civil de Icapuí",
        "Delegacia de Polícia Civil de Icó",
        "Delegacia de Polícia Civil de Iguatu",
        "Delegacia de Polícia Civil de Ipaumirim",
        "Delegacia de Polícia Civil de Iracema",
        "Delegacia de Polícia Civil de Jaguaretama",
        "Delegacia de Polícia Civil de Jaguaribe",
        "Delegacia de Polícia Civil de Jaguaruana",
        "Delegacia de Polícia Civil de Jardim",
        "Delegacia de Polícia Civil de Jucás",
        "Delegacia de Polícia Civil de Lavras da Mangabeira",
        "Delegacia de Polícia Civil de Limoeiro do Norte",
        "Delegacia de Polícia Civil de Mauriti",
        "Delegacia de Polícia Civil de Milagres",
        "Delegacia de Polícia Civil de Missão Velha",
        "Delegacia de Polícia Civil de Mombaça",
        "Delegacia de Polícia Civil de Morada Nova",
        "Delegacia de Polícia Civil de Nova Olinda",
        "Delegacia de Polícia Civil de Orós",
        "Delegacia de Polícia Civil de Parambu",
        "Delegacia de Polícia Civil de Pedra Branca",
        "Delegacia de Polícia Civil de Penaforte",
        "Delegacia de Polícia Civil de Quiterianópolis",
        "Delegacia de Polícia Civil de Quixadá",
        "Delegacia de Polícia Civil de Quixeramobim",
        "Delegacia de Polícia Civil de Russas",
        "Delegacia de Polícia Civil de Saboeiro",
        "Delegacia de Polícia Civil de São João do Jaguaribe",
        "Delegacia de Polícia Civil de Senador Pompeu",
        "Delegacia de Polícia Civil de Solonópole",
        "Delegacia de Polícia Civil de Tabuleiro do Norte",
        "Delegacia de Polícia Civil de Tauá",
        "Delegacia de Polícia Civil de Várzea Alegre",
        "1ª Seccional do Interior Sul",
        "2ª Seccional do Interior Sul",
        "3ª Seccional do Interior Sul",
        "4ª Seccional do Interior Sul",
        "5ª Seccional do Interior Sul"
    ],
    "DPE": [
        "Delegacia de Polícia Civil de Assuntos Internos",
        "Delegacia de Polícia Civil de Capturas e Polinter",
        "Delegacia de Polícia Civil de Proteção ao Consumidor",
        "Delegacia de Polícia Civil de Proteção ao Meio Ambiente",
        "Delegacia de Polícia Civil de Proteção ao Turista",
        "Delegacia de Polícia Civil de Repressão aos Crimes Cibernéticos",
        "Delegacia de Polícia Civil do Aeroporto Pinto Martins",
        "Delegacia do Torcedor e dos Grandes Eventos"
    ],
    "DPGV": [
        "1ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "2ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "Delegacia de Polícia Civil da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Combate à Exploração da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Defesa da Mulher de Caucaia",
        "Delegacia de Polícia Civil de Defesa da Mulher de Crato",
        "Delegacia de Polícia Civil de Defesa da Mulher de Icó",
        "Delegacia de Polícia Civil de Defesa da Mulher de Iguatu",
        "Delegacia de Polícia Civil de Defesa da Mulher de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Defesa da Mulher de Maracanaú",
        "Delegacia de Polícia Civil de Defesa da Mulher de Pacatuba",
        "Delegacia de Polícia Civil de Defesa da Mulher de Quixadá",
        "Delegacia de Polícia Civil de Defesa da Mulher de Sobral",
        "Delegacia de Polícia Civil de Proteção ao Idoso e Pessoa com Deficiência",
        "Delegacia de Polícia Civil de Repressão aos Crimes de Intolerância Racial, Religiosa, por Identidade de Gênero ou Orientação Sexual"
    ],
    "DRA": [
        "Delegacia de Polícia Civil de Combate à Corrupção",
        "Delegacia de Polícia Civil de Combate aos Crimes Contra a Ordem Tributária",
        "Delegacia de Polícia Civil de Combate aos Crimes de Lavagem de Dinheiro"
    ],
    "DRCO": [
        "Delegacia de Combate ao Tráfico de Armas, Munições e Explosivos",
        "Delegacia de Polícia Civil de Narcóticos",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Norte",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Sul"
    ],
    "ASJ": ["Assessoria Jurídica"],
    "COGEP": [], 
    "COTIC": [], 
    "COLOG": [], 
    "CODIP": [], 
    "GAB": [], 
    "CORE": ["Coordenadoria de Operações e Recursos Especiais"]
};

// Mapeamento completo de Delegacias por Departamento (oficial PCCE)
export const DEPARTMENTS = {
    "DEPATRI": [
        "Delegacia de Polícia Civil Antissequestro",
        "Delegacia de Polícia Civil de Defraudações e Falsificações",
        "Delegacia de Polícia Civil de Roubos e Furtos",
        "Delegacia de Polícia Civil de Roubos e Furtos de Veículos"
    ],
    "DHPP": [
        "1ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "2ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "3ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "4ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "5ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "6ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "7ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "8ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "9ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "10ª Delegacia de Polícia Civil de Homicídios e Proteção à Pessoa",
        "Delegacia de Polícia Civil de Homicídios Contra Agentes de Segurança Pública",
        "Delegacia de Polícia Civil de Pessoas Desaparecidas"
    ],
    "DPC": [
        "1ª Delegacia de Polícia Civil da Capital",
        "2ª Delegacia de Polícia Civil da Capital",
        "3ª Delegacia de Polícia Civil da Capital",
        "4ª Delegacia de Polícia Civil da Capital",
        "5ª Delegacia de Polícia Civil da Capital",
        "6ª Delegacia de Polícia Civil da Capital",
        "7ª Delegacia de Polícia Civil da Capital",
        "8ª Delegacia de Polícia Civil da Capital",
        "9ª Delegacia de Polícia Civil da Capital",
        "10ª Delegacia de Polícia Civil da Capital",
        "11ª Delegacia de Polícia Civil da Capital",
        "12ª Delegacia de Polícia Civil da Capital",
        "13ª Delegacia de Polícia Civil da Capital",
        "14ª Delegacia de Polícia Civil da Capital",
        "15ª Delegacia de Polícia Civil da Capital",
        "16ª Delegacia de Polícia Civil da Capital",
        "17ª Delegacia de Polícia Civil da Capital",
        "18ª Delegacia de Polícia Civil da Capital",
        "19ª Delegacia de Polícia Civil da Capital",
        "20ª Delegacia de Polícia Civil da Capital",
        "21ª Delegacia de Polícia Civil da Capital",
        "22ª Delegacia de Polícia Civil da Capital",
        "23ª Delegacia de Polícia Civil da Capital",
        "24ª Delegacia de Polícia Civil da Capital",
        "25ª Delegacia de Polícia Civil da Capital",
        "1ª Seccional da Capital",
        "2ª Seccional da Capital",
        "3ª Seccional da Capital",
        "4ª Seccional da Capital",
        "5ª Seccional da Capital"
    ],
    "DPM": [
        "1ª Delegacia de Polícia Civil de Caucaia",
        "2ª Delegacia de Polícia Civil de Caucaia",
        "3ª Delegacia de Polícia Civil de Caucaia",
        "4ª Delegacia de Polícia Civil de Caucaia",
        "5ª Delegacia de Polícia Civil de Caucaia",
        "1ª Delegacia de Polícia Civil de Maracanaú",
        "2ª Delegacia de Polícia Civil de Maracanaú",
        "3ª Delegacia de Polícia Civil de Maracanaú",
        "4ª Delegacia de Polícia Civil de Maracanaú",
        "5ª Delegacia de Polícia Civil de Maracanaú",
        "6ª Delegacia de Polícia Civil de Maracanaú",
        "1ª Delegacia de Polícia Civil de Pacatuba",
        "2ª Delegacia de Polícia Civil de Pacatuba",
        "Delegacia de Polícia Civil de Aquiraz",
        "Delegacia de Polícia Civil de Cascavel",
        "Delegacia de Polícia Civil de Chorozinho",
        "Delegacia de Polícia Civil de Eusébio",
        "Delegacia de Polícia Civil de Guaiúba",
        "Delegacia de Polícia Civil de Horizonte",
        "Delegacia de Polícia Civil de Itaitinga",
        "Delegacia de Polícia Civil de Maranguape",
        "Delegacia de Polícia Civil de Pacajus",
        "Delegacia de Polícia Civil de Paracuru",
        "Delegacia de Polícia Civil de Paraipaba",
        "Delegacia de Polícia Civil de Pindoretama",
        "Delegacia de Polícia Civil de São Gonçalo do Amarante",
        "Delegacia de Polícia Civil de Trairí",
        "1ª Seccional da Região Metropolitana",
        "2ª Seccional da Região Metropolitana",
        "3ª Seccional da Região Metropolitana",
        "4ª Seccional da Região Metropolitana",
        "5ª Seccional da Região Metropolitana",
        "6ª Seccional da Região Metropolitana"
    ],
    "DPI NORTE": [
        "1ª Delegacia de Polícia Civil de Sobral",
        "2ª Delegacia de Polícia Civil de Sobral",
        "Delegacia de Civil Polícia de Independência",
        "Delegacia de Polícia Civil de Acaraú",
        "Delegacia de Polícia Civil de Amontada",
        "Delegacia de Polícia Civil de Aracoiaba",
        "Delegacia de Polícia Civil de Barreira",
        "Delegacia de Polícia Civil de Baturité",
        "Delegacia de Polícia Civil de Bela Cruz",
        "Delegacia de Polícia Civil de Boa Viagem",
        "Delegacia de Polícia Civil de Camocim",
        "Delegacia de Polícia Civil de Canindé",
        "Delegacia de Polícia Civil de Chaval",
        "Delegacia de Polícia Civil de Coreaú",
        "Delegacia de Polícia Civil de Crateús",
        "Delegacia de Polícia Civil de Cruz",
        "Delegacia de Polícia Civil de Forquilha",
        "Delegacia de Polícia Civil de Granja",
        "Delegacia de Polícia Civil de Guaraciaba do Norte",
        "Delegacia de Polícia Civil de Guaramiranga",
        "Delegacia de Polícia Civil de Ipu",
        "Delegacia de Polícia Civil de Ipueiras",
        "Delegacia de Polícia Civil de Itapajé",
        "Delegacia de Polícia Civil de Itapipoca",
        "Delegacia de Polícia Civil de Itarema",
        "Delegacia de Polícia Civil de Jijoca de Jericoacoara",
        "Delegacia de Polícia Civil de Marco",
        "Delegacia de Polícia Civil de Massapê",
        "Delegacia de Polícia Civil de Monsenhor Tabosa",
        "Delegacia de Polícia Civil de Nova Russas",
        "Delegacia de Polícia Civil de Novo Oriente",
        "Delegacia de Polícia Civil de Ocara",
        "Delegacia de Polícia Civil de Pacujá",
        "Delegacia de Polícia Civil de Pentecoste",
        "Delegacia de Polícia Civil de Redenção",
        "Delegacia de Polícia Civil de Santa Quitéria",
        "Delegacia de Polícia Civil de Santana do Acaraú",
        "Delegacia de Polícia Civil de São Benedito",
        "Delegacia de Polícia Civil de Tamboril",
        "Delegacia de Polícia Civil de Tianguá",
        "Delegacia de Polícia Civil de Ubajara",
        "Delegacia de Polícia Civil de Uruburetama",
        "Delegacia de Polícia Civil de Uruoca",
        "Delegacia de Polícia Civil de Varjota",
        "Delegacia de Polícia Civil de Viçosa do Ceará",
        "1ª Seccional do Interior Norte",
        "2ª Seccional do Interior Norte",
        "3ª Seccional do Interior Norte",
        "4ª Seccional do Interior Norte"
    ],
    "DPI SUL": [
        "1ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "2ª Delegacia de Polícia Civil de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Acopiara",
        "Delegacia de Polícia Civil de Alto Santo",
        "Delegacia de Polícia Civil de Aracati",
        "Delegacia de Polícia Civil de Araripe",
        "Delegacia de Polícia Civil de Assaré",
        "Delegacia de Polícia Civil de Aurora",
        "Delegacia de Polícia Civil de Banabuiú",
        "Delegacia de Polícia Civil de Barbalha",
        "Delegacia de Polícia Civil de Barro",
        "Delegacia de Polícia Civil de Beberibe",
        "Delegacia de Polícia Civil de Brejo Santo",
        "Delegacia de Polícia Civil de Campos Sales",
        "Delegacia de Polícia Civil de Caririaçu",
        "Delegacia de Polícia Civil de Cedro",
        "Delegacia de Polícia Civil de Crato",
        "Delegacia de Polícia Civil de Farias Brito",
        "Delegacia de Polícia Civil de Icapuí",
        "Delegacia de Polícia Civil de Icó",
        "Delegacia de Polícia Civil de Iguatu",
        "Delegacia de Polícia Civil de Ipaumirim",
        "Delegacia de Polícia Civil de Iracema",
        "Delegacia de Polícia Civil de Jaguaretama",
        "Delegacia de Polícia Civil de Jaguaribe",
        "Delegacia de Polícia Civil de Jaguaruana",
        "Delegacia de Polícia Civil de Jardim",
        "Delegacia de Polícia Civil de Jucás",
        "Delegacia de Polícia Civil de Lavras da Mangabeira",
        "Delegacia de Polícia Civil de Limoeiro do Norte",
        "Delegacia de Polícia Civil de Mauriti",
        "Delegacia de Polícia Civil de Milagres",
        "Delegacia de Polícia Civil de Missão Velha",
        "Delegacia de Polícia Civil de Mombaça",
        "Delegacia de Polícia Civil de Morada Nova",
        "Delegacia de Polícia Civil de Nova Olinda",
        "Delegacia de Polícia Civil de Orós",
        "Delegacia de Polícia Civil de Parambu",
        "Delegacia de Polícia Civil de Pedra Branca",
        "Delegacia de Polícia Civil de Penaforte",
        "Delegacia de Polícia Civil de Quiterianópolis",
        "Delegacia de Polícia Civil de Quixadá",
        "Delegacia de Polícia Civil de Quixeramobim",
        "Delegacia de Polícia Civil de Russas",
        "Delegacia de Polícia Civil de Saboeiro",
        "Delegacia de Polícia Civil de São João do Jaguaribe",
        "Delegacia de Polícia Civil de Senador Pompeu",
        "Delegacia de Polícia Civil de Solonópole",
        "Delegacia de Polícia Civil de Tabuleiro do Norte",
        "Delegacia de Polícia Civil de Tauá",
        "Delegacia de Polícia Civil de Várzea Alegre",
        "1ª Seccional do Interior Sul",
        "2ª Seccional do Interior Sul",
        "3ª Seccional do Interior Sul",
        "4ª Seccional do Interior Sul",
        "5ª Seccional do Interior Sul"
    ],
    "DPE": [
        "Delegacia de Polícia Civil de Assuntos Internos",
        "Delegacia de Polícia Civil de Capturas e Polinter",
        "Delegacia de Polícia Civil de Proteção ao Consumidor",
        "Delegacia de Polícia Civil de Proteção ao Meio Ambiente",
        "Delegacia de Polícia Civil de Proteção ao Turista",
        "Delegacia de Polícia Civil de Repressão aos Crimes Cibernéticos",
        "Delegacia de Polícia Civil do Aeroporto Pinto Martins",
        "Delegacia do Torcedor e dos Grandes Eventos"
    ],
    "DPGV": [
        "1ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "2ª Delegacia de Polícia Civil de Defesa da Mulher de Fortaleza",
        "Delegacia de Polícia Civil da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Combate à Exploração da Criança e do Adolescente",
        "Delegacia de Polícia Civil de Defesa da Mulher de Caucaia",
        "Delegacia de Polícia Civil de Defesa da Mulher de Crato",
        "Delegacia de Polícia Civil de Defesa da Mulher de Icó",
        "Delegacia de Polícia Civil de Defesa da Mulher de Iguatu",
        "Delegacia de Polícia Civil de Defesa da Mulher de Juazeiro do Norte",
        "Delegacia de Polícia Civil de Defesa da Mulher de Maracanaú",
        "Delegacia de Polícia Civil de Defesa da Mulher de Pacatuba",
        "Delegacia de Polícia Civil de Defesa da Mulher de Quixadá",
        "Delegacia de Polícia Civil de Defesa da Mulher de Sobral",
        "Delegacia de Polícia Civil de Proteção ao Idoso e Pessoa com Deficiência",
        "Delegacia de Polícia Civil de Repressão aos Crimes de Intolerância Racial, Religiosa, por Identidade de Gênero ou Orientação Sexual"
    ],
    "DRA": [
        "Delegacia de Polícia Civil de Combate à Corrupção",
        "Delegacia de Polícia Civil de Combate aos Crimes Contra a Ordem Tributária",
        "Delegacia de Polícia Civil de Combate aos Crimes de Lavagem de Dinheiro"
    ],
    "DRCO": [
        "Delegacia de Combate ao Tráfico de Armas, Munições e Explosivos",
        "Delegacia de Polícia Civil de Narcóticos",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Norte",
        "Delegacia de Polícia Civil de Repressão às Ações Criminosas Organizadas do Interior Sul"
    ],
    "ASJ": ["Assessoria Jurídica"],
    "CORE": ["Coordenadoria de Operações e Recursos Especiais"],
    "DTO": ["DTO"],
    "CODIP": ["CODIP"],
    "COTIC": ["COTIC"],
    "COGEP": ["COGEP"],
    "GDGPC": ["GDGPC"],
    "AESP": ["AESP"],
    "COAFI": ["COAFI"],
    "CIOPAER": ["CIOPAER"],
    "ASCON": ["ASCON"],
    "COREG": ["COREG"]
};

export const PAY_RATES = {
    "OIP": {
        "A": { dia: 34.42, noite: 44.75 },
        "B": { dia: 34.42, noite: 44.75 },
        "C": { dia: 34.42, noite: 44.75 },
        "D": { dia: 34.42, noite: 44.75 }
    },
    "DPC": {
        "Especial": { dia: 48.18, noite: 62.63 }
    }
};


export const AIS_OPTIONS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12, 13,23, 24, 25];
export const DPC_LIST = ["KLEVER FARIAS", "ALCEU VIANA", "HUGGO LEONARDO", "LUIS JUNIOR", "EVNA AMERICA", "ROBERTA FROTA", "JOÃO GABRIEL", "KEYLA LACERDA", "WILSON CAMELO", "JULIUS BERNARDO"];
export const OIP_LIST = ["JARBAS", "LUCAS", "PAULO JUNIOR", "ALEX", "ROGERIO", "JOÃO PAULO CAVALCANTE TEIXEIRA"];
export const BRIEFING_LOCATIONS = ["Polícia Civil - CISP", ...DEPARTMENTS.DPC];
export const WEAPON_TYPES = ["PISTOLA", "REVÓLVER", "CARABINA", "METRALHADORA", "FUZIL", "ESCOPETA"];
export const AMMO_TYPES = ["9mm", ".40", ".380", ".38", ".32", ".22", "12", "5.56", "7.62", ".50", ".30"];
export const DRUG_TYPES = ["MACONHA", "HAXIXE", "COCAÍNA", "HEROÍNA", "CRACK", "SKANK", "LSD", "ECSTASY", "ANFETAMINAS", "ANABOLIZANTES"];
export const PRISON_TYPES = { 'preventiva': 'Preventiva', 'temporaria': 'Temporária', 'definitiva': 'Definitiva', 'civil': 'Civil', 'flagrante': 'Flagrante' };
export const DEFAULT_VAGAS_RULES = { night_weekday: 8, night_weekend_holiday: 10, day_weekend_holiday: 2 };

export const AIS_BAIRROS = {
       "1": ["ALDEOTA", "VARJOTA", "PRAIA DE IRACEMA", "MEIRELES", "VICENTE PINZON", "CAIS DO PORTO", "MUCURIPE"],
    "2": ["CONJUNTO CEARÁ I E II", "GENIBAÚ", "GRANJA PORTUGAL", "BOM JARDIM", "GRANJA LISBOA", "SIQUEIRA"],
    "3": ["MESSEJANA", "ANCURÍ", "PEDRAS", "BARROSO", "SANTA MARIA", "JANGURUSSU", "CONJUNTO PALMEIRAS", "CURIÓ", "LAGOA REDONDA", "GUAJERU", "SÃO BENTO", "PAUPINA", "COAÇÚ"],
    "4": ["ÁLVARO WEYNE", "VILA ELLERY", "CARLITO PAMPLONA", "MONTE CASTELO", "FARIAS BRITO", "SÃO GERARDO", "JACARECANGA", "CENTRO", "MOURA BRASIL"],
    "5": ["PARANGABA", "VILA PERY", "ITAOCA", "ITAPERI", "DENDÊ", "PANAMERICANO", "JARDIM AMÉRICA", "BENFICA", "DEMÓCRITO ROCHA", "COUTO FERNANDES", "MONTESE", "DAMAS", "BOM FUTURO", "VILA UNIÃO", "JOSÉ BONIFÁCIO", "PARREÃO", "FÁTIMA", "SERRINHA", "AEROPORTO"],
    "6": ["ANTÔNIO BEZERRA", "QUINTINO CUNHA", "OLAVO OLIVEIRA", "PADRE ANDRADE", "BELA VISTA", "PRESIDENTE KENNEDY", "PARQUELÂNDIA", "AMADEU FURTADO", "PARQUE ARAXÁ", "RODOLFO TEÓFILO", "BOM SUCESSO", "JOÃO XXIII", "JÓQUEI CLUBE", "HENRIQUE JORGE", "AUTRAN NUNES", "PICI", "DOM LUSTOSA"],
    "7": ["CIDADE DOS FUNCIONÁRIOS", "CAJAZEIRAS", "ALTO DA BALANÇA", "JARDIM DAS OLIVEIRAS", "AEROLÂNDIA", "EDSON QUEIROZ", "SABIAGUABA", "CAMBEBA", "JOSÉ DE ALENCAR", "PARQUE IRACEMA", "PARQUE MANIBURA", "SAPIRANGA", "PASSARÉ", "PARQUE DOIS IRMÃOS", "DIAS MACEDO", "BOA VISTA"],
    "8": ["PIRAMBU", "CRISTO REDENTOR", "FLORESTA", "JARDIM IRACEMA", "VILA VELHA", "JARDIM GUANABARA", "BARRA DO CEARÁ"],
    "9": ["CONJ. JOSÉ WALTER", "PLANALTO AÍRTON SENA", "MONDUBIM", "NOVO MONDUBIM", "CONJUNTO ESPERANÇA", "CANINDEZINHO", "VILA MANOEL SÁTIRO", "PRESIDENTE VARGAS", "PARQUE SÃO JOSÉ", "MARAPONGA", "JARDIM CEARENSE", "ARACAPÉ", "PARQUE SANTA ROSA"],
    "10": ["GUARARAPES", "ENG. LUCIANO CAVALCANTE", "SÃO JOÃO DO TAUAPE", "SALINAS", "JOAQUIM TÁVORA", "DIONÍSIO TORRES", "PAPICU", "LOURDES", "CIDADE 2000", "PRAIA DO FUTURO I E II", "COCÓ", "MANOEL DIAS BRANCO"],
    "11": ["CENTRO", "CIGANA", "NOVA CIDADE", "AÇUDE", "PARQUE SOLEDADE", "PARQUE SÃO GERARDO", "PADRE JÚLIA MARIA I E II", "ITAMBÉ I E II", "PLANALTO CAUCAIA", "PABUSSU I", "NOVO PABUSSU", "IPAUMIRIM", "BOM JESUS", "CAPUAN", "GENIPABU", "JANDAIGUABA", "PADRE ROMUALDO", "PICUÍ (CONJUNTO METROPOLITANO)", "CONJ PATRÍCIA GOMES", "CABATAN", "CURICACA", "CATUANA", "SÍTIOS NOVOS", "CIPÓ", "GARROTE", "ALTO DO GARROTE E GRILO", "COITÉ/PEDREIRAS", "ASSENTAMENTO LAGOA DA SERRA", "JUREMA", "CONJ. MIRANTE DO SOL POENTE", "CONJ. JURUPARI I E II", "PARQUE POTIRA I E II", "PARQUE GUADALAJARA", "CONJ. TABAPUÁ", "CONJ. TABAPUÁ BRASÍLIA 1", "CONJ. TABAPUÁ BRASÍLIA 2", "LOTEAMENTO PARQUE IPIRANGA", "PARQUE DAS NAÇÕES", "CONJ. SÃO MIGUEL", "CONJ. NOVO SÃO MIGUEL", "VILA MOSQUITO", "VILA NOVA", "CONJ. MARECHAL RONDON", "PARQUE ALBANO E CAMPOS DOS CARIOCAS", "ICARAÍ", "GUAJIRU", "PACHECO", "ÁREA VERDE I E II", "BARRA NOVA", "DEODATO", "MUCUMBA I E II", "DUNAS", "PARQUE LEBLON E IPARANA", "CONJ. NOVA METRÓPOLE", "CAMPO GRANDE", "ARIANÓPOLIS", "ELDORADO", "METRÓPOLE V", "URUCUTUBA", "TAQUARA", "MIRAMBÉ", "TUCUNDUBA", "BOM PRINCÍPIO I E II", "FAZENDA FEIJÃO", "JARANDRAGOEIRA", "CARAUÇANGA", "CONJ. ARATURI", "CONJ. NOVO PARAÍSO", "ESPLANADA DO ARATURI E LAGOA DOS PORCOS", "CUMBUCO", "LAGOA DO BANANA", "LAGOA DO CAUÍPE", "TABUBA", "CRISTALINAS", "CARAÚBAS", "PIRAPORA", "TANUPABA", "PARAZINHO", "LAGOA DO PARNAMIRIM", "LAGOA DO BARRO", "GUARARU E CARAÚBAS"],
    "12": ["CONJ. JEREISSATI I", "CONJ. JEREISSATI II (ATÉ A RUA 64)", "SERRA DO MARACANAÚ", "SANTO ANTÔNIO DO PITAGUARY", "LOTEAMENTO MARACANAÚ SUL", "OLHO D'ÁGUA DE CIMA", "OLHO D'ÁGUA DE BAIXO", "OLHO D'ÁGUA DOS PRATAS", "ESTRADA DA TANGUEIRA", "FURNA DA ONÇA", "ATERRO SANITÁRIO", "MUTIRÃO VIDA NOVA", "COLÔNIA ANTÔNIO JUSTA", "FÓRUM DO MARACANAÚ", "OLARIA", "HORTO", "ESCOLA DE MENORES", "PICADAS", "RESIDENCIAIS SÃO FRANCISCO", "SANTA MARTA", "BELA VISTA", "JARDIM DO AMOR", "ALTO DA MANGUEIRA", "BOA VISTA", "COQUEIRAL", "CENTRO", "PIRATININGA (ATÉ A RUA PERU)", "CONJUNTO INDUSTRIAL", "ESPLANADA MONDUBIM E PARTE DO ARACAPÉ", "ACARACUZINHO", "JAÇANAÚ", "PARQUE JARI", "PARQUE TIJUCA", "ALTO ALEGRE I", "ALTO ALEGRE II", "SANTA MARTA", "SANTO SÁTIRO", "NOVO ORIENTE", "SIQUEIRA", "CONJUNTO TIMBÓ", "DISTRITO INDUSTRIAL I E II", "CÁGADO", "MUCUNÃ", "PARQUE LUZARDO VIANA", "PAU SERRADO", "RESIDENCIAL MARACANAÚ", "PIRATININGA", "NOVO MARACANAÚ", "JENIPAPEIRO", "COQUEIRAL", "MARACANANZINHO", "PAJUÇARA", "JARDIM BANDEIRANTES", "BOA ESPERANÇA", "PLANALTO CIDADE NOVA", "DISTRITO INDUSTRIAL III"],
    "13": ["AQUIRAZ", "CASCAVEL", "EUSÉBIO", "PINDORETAMA"],
    "23": ["SG AMARANTE", "PARACURU", "PARAIPABA", "TRAIRI", "SÃO LUIZ DO CURU"],
    "24": ["PACATUBA", "GUAIÚBA", "MARANGUAPE", "JEREISSATI II", "CAMPOS DO JORDÃO", "CONJ. SANTA MARTA", "CONJ. SÃO FRANCISCO", "CONJ. BOM FUTURO", "PLANALTO DO BENJAMIM", "PAVUNA", "JEREISSATI III", "MONGUBA"],
    "25": ["CHOROZINHO", "HORIZONTE", "ITAITINGA", "PACAJUS"]
}

// Outros órgãos e siglas estaduais
export const OUTROS_ORGAOS = ["Ministério Público", "Polícia Civil de Outros Estados"];
export const SIGLAS_ESTADOS = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"];

// Órgãos Externos que podem solicitar operações
export const ORGAOS_EXTERNOS = {
    "MPCE - Ministério Público do Ceará": [],
    "MPPE - Ministério Público de Pernambuco": [],
    "MPBA - Ministério Público da Bahia": [],
    "MPPI - Ministério Público do Piauí": [],
    "PCRN - Polícia Civil do Rio Grande do Norte": [],
    "PCPB - Polícia Civil da Paraíba": [],
    "PCPE - Polícia Civil de Pernambuco": [],
    "PCBA - Polícia Civil da Bahia": [],
    "PCPI - Polícia Civil do Piauí": [],
    "PCMA - Polícia Civil do Maranhão": [],
    "Polícia Federal": [],
    "PRF - Polícia Rodoviária Federal": [],
    "Receita Federal": [],
    "SEFAZ - Secretaria da Fazenda": []
};
export const TIPOS_APOIO = ["Cartório", "Inteligência", "Apoio Logístico"];
export const RESTRICTED_DEPTS = ["COGEP", "COTIC", "COLOG", "CODIP", "GAB", "CORE"];

// Taxas de hora extra
export const HORA_EXTRA_RATES = {
    dpc: { slot1: 47.70, slot2: 62.01 },
    oip: { slot1: 34.08, slot2: 44.30 }
};

// Dados de demandas para operações
export const DEMAND_DATA = {
    tiposPenais: ["Homicídio", "Tráfico de Drogas", "ORCRIM Lavagem de Dinheiro", "Roubo", "Furto", "Outros"],
    modalidades: ["Mandado de Busca e Apreensão Domiciliar", "Mandado de Prisão Preventiva", "Mandado de Prisão Temporária", "Sequestro/Bloqueio de Bens", "Outros"],
    faccoes: ["CV", "GDE", "Neutros", "PCC", "TCP", "Outros"],
    alvosSensiveis: ["Mulher", "Policial", "Político", "Advogado", "Servidor Público", "Outros"],
    apoioOutrosOrgaos: ["MP", "Polícia Militar", "Polícia Federal", "Polícia Rodoviária Federal", "Receita Federal", "SEFAZ", "AMC", "Guarda Municipal"]
};