# Generated by Django 4.2.7 on 2025-12-03 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delegacias',
                'ordering': ['departamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Em Análise', 'Em Análise'), ('Aprovada', 'Aprovada'), ('Pendente (Conflito)', 'Pendente (Conflito)'), ('Rejeitada', 'Rejeitada')], default='Em Análise', max_length=20)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_aprovadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-?\\d{4}$', 'Placa inválida')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('km_atual', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('delegacia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas', to='api.delegacia')),
            ],
            options={
                'verbose_name_plural': 'Viaturas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('day', 'Diurno (08:00 - 20:00)'), ('night', 'Noturno (19:00 - 01:00)')], max_length=10)),
                ('posicoes_disponiveis', models.IntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Disponível', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('delegacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='api.delegacia')),
            ],
            options={
                'ordering': ['data', 'turno'],
                'unique_together': {('data', 'turno', 'delegacia')},
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Matrícula deve ter 8 dígitos')])),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(choices=[('Praça', 'Praça'), ('Oficial', 'Oficial')], max_length=20)),
                ('cargo', models.CharField(choices=[('Policial Civil', 'Policial Civil'), ('Delegado', 'Delegado'), ('Inspetor', 'Inspetor'), ('Escrivão', 'Escrivão'), ('Investigador', 'Investigador')], max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('delegacia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policiais', to='api.delegacia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Policiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Planejada', 'Planejada'), ('Em Execução', 'Em Execução'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Planejada', max_length=20)),
                ('ais', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros', models.CharField(blank=True, max_length=500, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='api.equipe')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='chefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='api.policial'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(related_name='equipes_participadas', to='api.policial'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='api.vaga'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='api.viatura'),
        ),
        migrations.AddField(
            model_name='delegacia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacias', to='api.departamento'),
        ),
        migrations.CreateModel(
            name='Convoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Planejado', max_length=20)),
                ('ais', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros', models.CharField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convoios_dpc', to='api.policial')),
                ('oip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convoios_oip', to='api.policial')),
                ('operacoes', models.ManyToManyField(blank=True, related_name='convoios', to='api.operacao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='delegacia',
            unique_together={('nome', 'departamento')},
        ),
    ]
