# Generated by Django 4.2.7 on 2025-12-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comboio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Planejado', max_length=20)),
                ('ais', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros', models.CharField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comboios_dpc', to='api.policial')),
                ('oip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comboios_oip', to='api.policial')),
                ('operacoes', models.ManyToManyField(blank=True, related_name='comboios', to='api.operacao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.DeleteModel(
            name='Convoio',
        ),
    ]
