# Generated by Django 4.2.26 on 2025-12-15 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_convoio_to_comboio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmou_presenca', models.BooleanField(default=False)),
                ('hora_retorno', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chefe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_operacao_lider', to='api.policial')),
                ('delegacia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_operacao', to='api.delegacia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_operacao', to='api.departamento')),
                ('membros', models.ManyToManyField(blank=True, related_name='equipes_operacao_membro', to='api.policial')),
            ],
            options={
                'verbose_name': 'Equipe da Operação',
                'verbose_name_plural': 'Equipes da Operação',
                'ordering': ['departamento', 'delegacia'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_operacao', models.CharField(choices=[('Interna', 'Operação Interna (Sem Apoio)'), ('Com Apoio', 'Operação com Apoio Externo')], default='Interna', max_length=20)),
                ('objetivo', models.TextField()),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('data_hora_briefing', models.DateTimeField(help_text='Data/hora do briefing - após isso, policiais podem ver alvos')),
                ('local_concentracao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovada pelo DTO', 'Aprovada pelo DTO'), ('Reprovada pelo DTO', 'Reprovada pelo DTO'), ('Em Execução', 'Em Execução'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Rascunho', max_length=30)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('custo_planejado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('departamento_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_solicitadas', to='api.departamento')),
                ('departamentos_apoio', models.ManyToManyField(blank=True, help_text='Departamentos convidados para apoiar', related_name='operacoes_apoio', to='api.departamento')),
                ('responsavel_custo', models.ForeignKey(blank=True, help_text='Departamento responsável pelo custo (Solicitante se interna, DTO se apoio)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_custeadas', to='api.departamento')),
                ('responsavel_operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_responsavel', to='api.policial')),
            ],
            options={
                'verbose_name': 'Operação Policial',
                'verbose_name_plural': 'Operações Policiais',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SubstitutoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutos', to='api.equipeoperacao')),
                ('policial_planejado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_planejadas', to='api.policial')),
                ('policial_substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_realizadas', to='api.policial')),
            ],
            options={
                'verbose_name': 'Substituto',
                'verbose_name_plural': 'Substitutos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Prisão', 'Prisão'), ('Apreensão', 'Apreensão'), ('Mandado Cumprido', 'Mandado Cumprido'), ('Arma Apreendida', 'Arma Apreendida'), ('Droga Apreendida', 'Droga Apreendida'), ('Veículo Recuperado', 'Veículo Recuperado'), ('Outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=1)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipeoperacao')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.operacaopolicial')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado da Operação',
                'verbose_name_plural': 'Resultados da Operação',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.AddField(
            model_name='equipeoperacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_operacao', to='api.operacaopolicial'),
        ),
        migrations.AddField(
            model_name='equipeoperacao',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_operacao', to='api.viatura'),
        ),
        migrations.CreateModel(
            name='AporteFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dpc', models.IntegerField(default=0, help_text='Total de DPCs na operação')),
                ('total_oip', models.IntegerField(default=0, help_text='Total de OIPs na operação')),
                ('total_efetivo', models.IntegerField(default=0, help_text='Total de efetivo')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento')),
                ('operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aporte', to='api.operacaopolicial')),
            ],
            options={
                'verbose_name': 'Aporte Financeiro',
                'verbose_name_plural': 'Aportes Financeiros',
            },
        ),
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Pessoa', 'Pessoa'), ('Local', 'Local/Endereço'), ('Veículo', 'Veículo'), ('Organização', 'Organização Criminosa')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('dossie_pdf', models.FileField(blank=True, null=True, upload_to='dossies/')),
                ('visivel_apos_briefing', models.BooleanField(default=True, help_text='Se True, só visível após briefing')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alvos', to='api.operacaopolicial')),
            ],
            options={
                'verbose_name_plural': 'Alvos',
                'ordering': ['nome'],
            },
        ),
    ]
