# Generated by Django 4.2.26 on 2026-01-05 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_equipeoperacao_operacaopolicial_substitutooperacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('ORDINARIO', 'Serviço Ordinário'), ('EXTRAORDINARIO', 'Serviço Extraordinário')], max_length=20)),
                ('tipo_policial', models.CharField(choices=[('OIP', 'OIP - Oficiais de Plantão'), ('DPC', 'DPC - Delegado de Polícia Civil')], max_length=10)),
                ('quantidade_policiais', models.IntegerField(help_text='Quantidade total de policiais para este evento')),
                ('com_aporte_financeiro', models.BooleanField(default=False, help_text='Se haverá aporte financeiro para esta operação')),
                ('horario_inicio_delegacia', models.TimeField()),
                ('horario_fim_delegacia', models.TimeField()),
                ('escalas_definidas', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('delegacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_participacao', to='api.delegacia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_participacao', to='api.departamento')),
            ],
            options={
                'verbose_name': 'Departamento no Evento',
                'verbose_name_plural': 'Departamentos nos Eventos',
                'ordering': ['evento', 'departamento'],
            },
        ),
        migrations.CreateModel(
            name='EventoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('CARNAVAL', 'Carnaval'), ('REVEILLON', 'Réveillon'), ('FESTA_PADROEIRO', 'Festa do Padroeiro'), ('SHOW', 'Show/Evento Musical'), ('ESPORTIVO', 'Evento Esportivo'), ('OUTRO', 'Outro')], max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('local', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Em Planejamento'), ('CADASTRO_INICIAL', 'Cadastro Inicial'), ('DEFININDO_ESCALAS', 'Definindo Escalas'), ('APROVADO', 'Aprovado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJAMENTO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação de Evento',
                'verbose_name_plural': 'Operações de Evento',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EscalaPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Ex: Policial 1, Policial 2, etc', max_length=50)),
                ('data_servico', models.DateField()),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, help_text='Valor/hora para cálculo de custo', max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.departamentoevento')),
                ('policial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_evento', to='api.policial')),
            ],
            options={
                'verbose_name': 'Escala de Policial',
                'verbose_name_plural': 'Escalas de Policiais',
                'ordering': ['departamento_evento', 'data_servico', 'horario_entrada'],
            },
        ),
        migrations.AddField(
            model_name='departamentoevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_participantes', to='api.eventooperacao'),
        ),
        migrations.AlterUniqueTogether(
            name='departamentoevento',
            unique_together={('evento', 'departamento', 'delegacia')},
        ),
    ]
