# Generated by Django 4.2.26 on 2026-01-08 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_departamentoevento_eventooperacao_escalapolicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jwt', models.TextField(help_text='Token JWT da sessão')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='api.policial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuários',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('coordenador', 'Coordenador'), ('policial', 'Policial')], default='policial', help_text='Nível de acesso do policial no sistema', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o policial pode acessar o sistema')),
                ('ultimo_acesso', models.DateTimeField(blank=True, help_text='Data e hora do último acesso ao sistema', null=True)),
                ('pode_criar_operacoes', models.BooleanField(default=False)),
                ('pode_aprovar_escalas', models.BooleanField(default=False)),
                ('pode_gerenciar_usuarios', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('policial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='api.policial')),
            ],
            options={
                'verbose_name': 'Perfil de Policial',
                'verbose_name_plural': 'Perfis de Policiais',
                'ordering': ['policial__nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('depatri', 'DEPATRI - Delegacia de Proteção ao Patrimônio'), ('dhpp', 'DHPP - Delegacia de Homicídios e Proteção à Pessoa'), ('dpc', 'DPC - Delegacia de Polícia da Criança'), ('coplan', 'COPLAN - Coordenadoria de Planejamento'), ('dpm', 'DPM - Delegacia de Proteção à Mulher'), ('dpi_norte', 'DPI Norte - Delegacia de Polícia de Investigações Norte'), ('dpi_sul', 'DPI Sul - Delegacia de Polícia de Investigações Sul'), ('dhpp_caucaia', 'DHPP Caucaia - Delegacia de Homicídios Caucaia'), ('dpe', 'DPE - Delegacia de Polícia Especializada'), ('dpgv', 'DPGV - Delegacia de Proteção a Grupos Vulneráveis'), ('dra', 'DRA - Delegacia Regional de Aquiraz'), ('drco', 'DRCO - Delegacia de Repressão ao Crime Organizado'), ('dto', 'DTO - Departamento de Transporte e Operações')], help_text='Sigla do departamento', max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o departamento pode acessar o sistema')),
                ('ultimo_acesso', models.DateTimeField(blank=True, help_text='Data e hora do último acesso ao sistema', null=True)),
                ('pode_ver_operacoes', models.BooleanField(default=True, help_text='Pode visualizar operações do departamento')),
                ('pode_responder_notificacoes', models.BooleanField(default=True, help_text='Pode responder a notificações do DTO')),
                ('pode_informar_efetivo', models.BooleanField(default=True, help_text='Pode informar efetivo disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='api.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_departamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Departamento',
                'verbose_name_plural': 'Perfis de Departamentos',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitacao_efetivo', 'Solicitação de Efetivo'), ('informacao', 'Informação'), ('alerta', 'Alerta'), ('urgente', 'Urgente')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('lida', 'Lida'), ('respondida', 'Respondida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_texto', models.TextField(blank=True)),
                ('efetivo_disponivel', models.IntegerField(blank=True, help_text='Quantidade de policiais disponíveis informada pelo departamento', null=True)),
                ('viaturas_disponiveis', models.IntegerField(blank=True, help_text='Quantidade de viaturas disponíveis', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais do departamento')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('de_departamento', models.ForeignKey(help_text='Departamento que enviou (geralmente DTO)', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to='api.perfildepartamento')),
                ('operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='api.operacaopolicial')),
                ('para_departamento', models.ForeignKey(help_text='Departamento destinatário', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to='api.perfildepartamento')),
            ],
            options={
                'verbose_name': 'Notificação de Departamento',
                'verbose_name_plural': 'Notificações de Departamentos',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['para_departamento', 'status', '-criada_em'], name='api_notific_para_de_2bc9c1_idx'), models.Index(fields=['operacao', '-criada_em'], name='api_notific_operaca_00deb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar_usuario', 'Criar Usuário'), ('editar_usuario', 'Editar Usuário'), ('deletar_usuario', 'Deletar Usuário'), ('ativar_usuario', 'Ativar Usuário'), ('desativar_usuario', 'Desativar Usuário'), ('alterar_role', 'Alterar Permissão'), ('criar_operacao', 'Criar Operação'), ('editar_operacao', 'Editar Operação'), ('deletar_operacao', 'Deletar Operação'), ('finalizar_operacao', 'Finalizar Operação'), ('criar_escala', 'Criar Escala'), ('editar_escala', 'Editar Escala'), ('deletar_escala', 'Deletar Escala'), ('aprovar_escala', 'Aprovar Escala'), ('criar_evento', 'Criar Evento'), ('editar_evento', 'Editar Evento'), ('deletar_evento', 'Deletar Evento'), ('login', 'Login'), ('logout', 'Logout'), ('falha_login', 'Falha no Login'), ('alterar_senha', 'Alterar Senha'), ('exportar_dados', 'Exportar Dados'), ('importar_dados', 'Importar Dados'), ('backup', 'Backup do Sistema'), ('alterar_configuracao', 'Alterar Configuração'), ('acesso_negado', 'Acesso Negado'), ('tentativa_acesso_nao_autorizado', 'Tentativa de Acesso Não Autorizado')], max_length=50)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('descricao', models.TextField(help_text='Descrição detalhada da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('url_acessada', models.TextField(blank=True)),
                ('dados_antes', models.JSONField(blank=True, help_text='Estado anterior do objeto', null=True)),
                ('dados_depois', models.JSONField(blank=True, help_text='Estado posterior do objeto', null=True)),
                ('dados_extras', models.JSONField(blank=True, help_text='Informações adicionais', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to='api.policial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_logaudi_timesta_99df92_idx'), models.Index(fields=['usuario', '-timestamp'], name='api_logaudi_usuario_0ecc2a_idx'), models.Index(fields=['acao', '-timestamp'], name='api_logaudi_acao_aa98a6_idx'), models.Index(fields=['nivel', '-timestamp'], name='api_logaudi_nivel_89f7b0_idx')],
            },
        ),
    ]
