# Generated by Django 4.2.26 on 2026-01-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sessaousuario_perfilpolicial_perfildepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaodepartamento',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_efetivo', 'Solicitação de Efetivo'), ('aprovacao_demanda', 'Aprovação de Demanda'), ('rejeicao_demanda', 'Rejeição de Demanda'), ('informacao', 'Informação'), ('alerta', 'Alerta'), ('urgente', 'Urgente')], max_length=30),
        ),
        migrations.CreateModel(
            name='DemandaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada da operação necessária')),
                ('justificativa', models.TextField(help_text='Justificativa para a operação')),
                ('local', models.CharField(help_text='Local da operação', max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(default='Fortaleza', max_length=100)),
                ('data_inicio_prevista', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente Aprovação'), ('em_analise', 'Em Análise pelo DTO'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('efetivo_solicitado', models.IntegerField(help_text='Quantidade de policiais necessários')),
                ('viaturas_solicitadas', models.IntegerField(default=0, help_text='Quantidade de viaturas necessárias')),
                ('necessita_apoio_outros_departamentos', models.BooleanField(default=False, help_text='Indica se precisa apoio de outros departamentos')),
                ('analisada_em', models.DateTimeField(blank=True, null=True)),
                ('parecer_dto', models.TextField(blank=True, help_text='Parecer do DTO sobre a demanda')),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição (se aplicável)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('analisada_por', models.ForeignKey(blank=True, help_text='Usuário DTO que analisou', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_analisadas', to='api.perfildepartamento')),
                ('departamento_solicitante', models.ForeignKey(help_text='Departamento que criou a demanda', on_delete=django.db.models.deletion.CASCADE, related_name='demandas_criadas', to='api.perfildepartamento')),
                ('operacao', models.ForeignKey(blank=True, help_text='Operação criada a partir desta demanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demanda_origem', to='api.operacaopolicial')),
            ],
            options={
                'verbose_name': 'Demanda de Operação',
                'verbose_name_plural': 'Demandas de Operações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='notificacaodepartamento',
            name='demanda',
            field=models.ForeignKey(blank=True, help_text='Demanda que originou esta notificação', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='api.demandaoperacao'),
        ),
        migrations.AddIndex(
            model_name='demandaoperacao',
            index=models.Index(fields=['status', '-criada_em'], name='api_demanda_status_80f683_idx'),
        ),
        migrations.AddIndex(
            model_name='demandaoperacao',
            index=models.Index(fields=['departamento_solicitante', '-criada_em'], name='api_demanda_departa_58a823_idx'),
        ),
        migrations.AddIndex(
            model_name='demandaoperacao',
            index=models.Index(fields=['prioridade', 'status'], name='api_demanda_priorid_64bdb4_idx'),
        ),
    ]
