# Generated by Django 4.2.7 on 2026-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_demanda_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('feriado_nacional', 'Feriado Nacional'), ('feriado_estadual', 'Feriado Estadual'), ('data_especial', 'Data Especial'), ('carnaval', 'Carnaval'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.AlterField(
            model_name='perfildepartamento',
            name='sigla',
            field=models.CharField(choices=[('depatri', 'DEPATRI - Delegacia de Proteção ao Patrimônio'), ('dhpp', 'DHPP - Delegacia de Homicídios e Proteção à Pessoa'), ('dpc', 'DPC - Delegacia de Polícia da Criança'), ('coplan', 'COPLAN - Coordenadoria de Plantões'), ('dpm', 'DPM - Delegacia de Proteção à Mulher'), ('dpi_norte', 'DPI Norte - Departamento de Polícias Interior Norte'), ('dpi_sul', 'DPI Sul - Departamento de Polícias Interior Sul'), ('dhpp_caucaia', 'DHPP Caucaia - Delegacia de Homicídios Caucaia'), ('dpe', 'DPE - Departamento de Polícias Especializadas'), ('dpgv', 'DPGV - Delegacia de Proteção a Grupos Vulneráveis'), ('dra', 'DRA - Departamento de Recuperação de Ativos'), ('drco', 'DRCO - Delegacia de Repressão ao Crime Organizado'), ('dto', 'DTO - Departamento Técnico Operacional'), ('gadel', 'GADEL - Gabinete')], help_text='Sigla do departamento', max_length=20, unique=True),
        ),
    ]
