# Generated by Django 4.2.7 on 2026-03-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_policial_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField()),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('substituto', 'Substituto'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='api.equipe')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='api.policial')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias_como_substituto', to='api.policial')),
            ],
            options={
                'verbose_name': 'Frequência de Policial',
                'verbose_name_plural': 'Frequências de Policiais',
                'ordering': ['-data_operacao'],
                'unique_together': {('equipe', 'policial', 'data_operacao')},
            },
        ),
    ]
