# Generated by Django 4.2.7 on 2026-03-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_frequencia_policial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField()),
                ('horario_inicial', models.DateTimeField()),
                ('horario_final', models.DateTimeField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.policial')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_operacao', 'policial'],
            },
        ),
    ]
