# Generated by Django 4.2.7 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_perfildepartamento_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaopolicial',
            name='plano_operacional',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
