# Generated by Django 4.2.7 on 2026-04-22 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_operacaopolicial_plano_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='matricula',
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\d{7}[\\dX]$',
                        'Matrícula deve ter 8 caracteres (7 números e o último pode ser X)',
                    )
                ],
            ),
        ),
    ]
