# Generated by Django 4.2.7 on 2026-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='restrito_adm_cadastra',
            field=models.BooleanField(default=False),
        ),
    ]
