# Generated by Django 4.2.7 on 2026-04-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_vaga_restrito_adm_cadastra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaga',
            unique_together={('data', 'turno', 'delegacia', 'restrito_adm_cadastra')},
        ),
    ]
