# Generated by Django 4.2.7 on 2026-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_vaga_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioComboio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convoy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('legacy_team_id', models.IntegerField(blank=True, null=True)),
                ('legacy_operation_id', models.IntegerField(blank=True, null=True)),
                ('data_operacao', models.DateField(db_index=True)),
                ('cycle_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('delegacia', models.CharField(blank=True, max_length=100, null=True)),
                ('ais', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros', models.JSONField(blank=True, default=list)),
                ('abordagens', models.JSONField(blank=True, default=dict)),
                ('prisoes', models.JSONField(blank=True, default=list)),
                ('procedimentos', models.JSONField(blank=True, default=dict)),
                ('apreensoes', models.JSONField(blank=True, default=dict)),
                ('escoltas', models.JSONField(blank=True, default=list)),
                ('mandados_prisao_diligenciados', models.IntegerField(default=0)),
                ('conducoes_averiguacao', models.IntegerField(default=0)),
                ('procedimento_escolta', models.TextField(blank=True, null=True)),
                ('homicidios_ais', models.BooleanField(blank=True, null=True)),
                ('submitted_by', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório de Comboio',
                'verbose_name_plural': 'Relatórios de Comboio',
                'ordering': ['-data_operacao', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='perfildepartamento',
            name='sigla',
            field=models.CharField(choices=[('depatri', 'DEPATRI - Departamento de Patrimônio'), ('dhpp', 'DHPP - Departamento de Homicídios e Proteção à Pessoa'), ('dpc', 'DPC - Departamento de Polícia da Criança'), ('coplan', 'COPLAN - Coordenadoria de Plantões'), ('dpm', 'DPM - Departamento de Proteção à Mulher'), ('dpi_norte', 'DPI Norte - Departamento de Polícias Interior Norte'), ('dpi_sul', 'DPI Sul - Departamento de Polícias Interior Sul'), ('dhpp_caucaia', 'DHPP Caucaia - Departamento de Homicídios Caucaia'), ('dpe', 'DPE - Departamento de Polícias Especializadas'), ('dpgv', 'DPGV - Departamento de Proteção a Grupos Vulneráveis'), ('dra', 'DRA - Departamento de Recuperação de Ativos'), ('drco', 'DRCO - Departamento de Repressão ao Crime Organizado'), ('dto', 'DTO - Departamento Técnico Operacional'), ('gadel', 'GADEL - Gabinete'), ('no_do_depatri', 'N.O DO DEPATRI - DEPATRI'), ('no_dpe', 'N.O DPE - DPE'), ('nucleo_meu_celular', 'NUCLEO MEU CELULAR - DEPATRI'), ('no_dhpp', 'N.O DHPP - DHPP'), ('no_aracati', 'N.O DE ARACATI - DPI SUL'), ('no_juazeiro_norte', 'N.O DE JUAZEIRO DO NORTE - DPI SUL'), ('no_quixada', 'N.O DE QUIXADA - DPI SUL'), ('no_iguatu', 'N.O DE IGUATU - DPI SUL'), ('no_taua', 'N.O DE TAUA - DPI SUL'), ('no_dpgv', 'N.O DPGV - DPGV'), ('no_capital', 'N.O DA CAPITAL - DPC'), ('no_dpi_norte', 'N.O DPI NORTE - DPI NORTE'), ('no_depatri', 'N.O DEPATRI - DEPATRI'), ('no_dra', 'N.O DRA - DRA'), ('ascoi', 'ASCOI - Assessoria de Controle Interno')], help_text='Sigla do departamento', max_length=20, unique=True),
        ),
    ]
